apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osuclassy-ingress
  namespace: osuclassy-dev
spec:
  rules:
    - host: api.osuclassy-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osuclassy-backend-service
                port:
                  number: 8000
    - host: osuclassy-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osuclassy-frontend-service
                port:
                  number: 3000
