import React, { ReactElement } from 'react'
import { Typography, TextContainer } from 'react-md'

export default function Home(): ReactElement {
  return (
    <TextContainer>
      <Typography type="headline-2">Hello World</Typography>
      <Typography type="body-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In cursus lacinia ante, eu sagittis urna vehicula pellentesque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec ante sagittis odio porttitor euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed iaculis orci vitae semper porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In quis lorem eros. Aenean ultrices mi ipsum, eu tempor diam dapibus non. Aliquam euismod ipsum eget sagittis consequat. Sed tincidunt rutrum tellus, quis tincidunt elit vestibulum et. Nam nec fringilla velit. Aliquam vel nisl tincidunt, lacinia eros et, euismod erat.</Typography>
      <Typography type="body-1">Morbi venenatis ac turpis eget pharetra. Mauris eros felis, condimentum nec sapien id, imperdiet scelerisque tellus. Vestibulum risus est, vulputate in neque in, venenatis commodo justo. Vestibulum placerat, ipsum sit amet bibendum convallis, enim libero congue nibh, at mollis ex turpis quis enim. Vivamus eu arcu at lorem gravida dignissim in sit amet neque. Praesent vel eros ut est malesuada mattis. Nunc eget dolor lacus. In viverra aliquam magna a euismod.</Typography>
      <Typography type="body-1">Proin eu vestibulum elit. Donec rhoncus tortor eu arcu interdum dapibus non placerat enim. Vivamus mollis, sem quis vehicula auctor, massa enim pretium nunc, sit amet porttitor nisi nisi nec turpis. Nulla sed velit nibh. Phasellus nec quam vulputate nulla sollicitudin lacinia id vitae diam. Curabitur convallis vel ante quis eleifend. Duis non sapien libero. Sed vitae facilisis metus. Fusce facilisis ante in arcu elementum dictum. Integer tempus nunc tellus, vel viverra mi tristique at. Nulla facilisi. Ut viverra sapien volutpat augue sollicitudin tempor. Aenean varius, eros quis auctor euismod, diam felis ornare augue, in venenatis tortor diam eu mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent hendrerit eros in consectetur tempor.</Typography>
      <Typography type="body-1">Integer augue risus, gravida et arcu ut, consequat rhoncus dolor. Aenean mollis aliquet suscipit. Aenean blandit faucibus mattis. Suspendisse eget est auctor, dignissim diam at, fermentum ligula. Nullam non ultricies felis. Nam volutpat interdum turpis id porttitor. Etiam odio purus, pharetra id vehicula eget, imperdiet eu erat. Vestibulum lacinia sollicitudin pulvinar. Nulla facilisi. Sed ut cursus nisl. Sed eu semper elit, ac condimentum tortor. In est risus, auctor ac tellus faucibus, laoreet dictum augue. Suspendisse tincidunt nisi sed leo finibus mattis. Mauris sed enim consequat nulla consequat tincidunt. Etiam accumsan nulla eget sem accumsan, sit amet laoreet ipsum fermentum.</Typography>
      <Typography type="body-1">Suspendisse vitae bibendum purus. Nulla gravida magna vitae purus hendrerit, quis mattis libero blandit. Morbi ornare bibendum orci, eget sodales nunc feugiat in. Curabitur id ex mattis, ultricies ligula quis, scelerisque arcu. Quisque at lectus gravida, porttitor eros ut, aliquet dolor. Aliquam mi leo, tincidunt in laoreet a, vulputate nec sem. Nunc nunc mi, condimentum at metus eget, consequat dignissim ante. Pellentesque efficitur vestibulum dui a porttitor. In malesuada sit amet risus et vestibulum.</Typography>
    </TextContainer>
  )
}
